defmodule Foodmap.Repo.Migrations.Maybe do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    drop_if_exists index(:place_users, [:user_id])

    rename table(:place_users), :user_id, to: :follower_id

    drop constraint(:place_users, "place_users_user_id_fkey")

    alter table(:place_users) do
      modify :follower_id,
             references(:users,
               column: :id,
               name: "place_users_follower_id_fkey",
               type: :uuid,
               prefix: "public",
               on_delete: :delete_all
             )
    end

    create index(:place_users, [:follower_id])
  end

  def down do
    drop_if_exists index(:place_users, [:follower_id])

    drop constraint(:place_users, "place_users_follower_id_fkey")

    alter table(:place_users) do
      modify :follower_id,
             references(:users,
               column: :id,
               name: "place_users_user_id_fkey",
               type: :uuid,
               prefix: "public",
               on_delete: :delete_all
             )
    end

    rename table(:place_users), :follower_id, to: :user_id

    create index(:place_users, [:user_id])
  end
end
