defmodule Foodmap.Repo.Migrations.Finalfina do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:places) do
      modify :lng, :float, null: false
      modify :lat, :float, null: false
    end
  end

  def down do
    alter table(:places) do
      modify :lat, :float, null: true
      modify :lng, :float, null: true
    end
  end
end
