defmodule Foodmap.Repo.Migrations.RemoveAddress do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:places) do
      remove :address
    end
  end

  def down do
    alter table(:places) do
      add :address, :text
    end
  end
end
