defmodule Foodmap.Repo.Migrations.PlaceUserRel do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:places, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :name, :text, null: false
      add :address, :text
      add :lat, :float
      add :lng, :float
    end

    create table(:place_users, primary_key: false) do
      add :place_id,
          references(:places,
            column: :id,
            name: "place_users_place_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :delete_all
          ), primary_key: true, null: false

      add :user_id,
          references(:users,
            column: :id,
            name: "place_users_user_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :delete_all
          ), primary_key: true, null: false
    end

    create index(:place_users, [:user_id])
  end

  def down do
    drop_if_exists index(:place_users, [:user_id])

    drop constraint(:place_users, "place_users_place_id_fkey")

    drop constraint(:place_users, "place_users_user_id_fkey")

    drop table(:place_users)

    drop table(:places)
  end
end
