defmodule Foodmap.Repo.Migrations.FixReferences do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    drop constraint(:place_users, "place_users_user_id_fkey")

    alter table(:place_users) do
      modify :user_id,
             references(:users,
               column: :id,
               name: "place_users_user_id_fkey",
               type: :uuid,
               prefix: "public",
               on_delete: :delete_all
             )
    end

    create index(:place_users, [:user_id])
  end

  def down do
    drop_if_exists index(:place_users, [:user_id])

    drop constraint(:place_users, "place_users_user_id_fkey")

    alter table(:place_users) do
      modify :user_id,
             references(:users,
               column: :id,
               name: "place_users_user_id_fkey",
               type: :uuid,
               prefix: "public"
             )
    end
  end
end
