defmodule Foodmap.Repo.Migrations.OtherRename2 do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    drop constraint(:place_users, "place_users_place_id_fkey")

    alter table(:place_users) do
      modify :place_id,
             references(:places,
               column: :id,
               name: "place_users_place_id_fkey",
               type: :uuid,
               prefix: "public",
               on_delete: :delete_all
             )
    end
  end

  def down do
    drop constraint(:place_users, "place_users_place_id_fkey")

    alter table(:place_users) do
      modify :place_id,
             references(:places,
               column: :id,
               name: "place_users_place_id_fkey",
               type: :uuid,
               prefix: "public"
             )
    end
  end
end
