defmodule Foodmap.Repo.Migrations.FixNames do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    rename table(:place_users), :place_id, to: :follower_id

    drop constraint(:place_users, "place_users_place_id_fkey")

    alter table(:place_users) do
      modify :follower_id,
             references(:places,
               column: :id,
               name: "place_users_follower_id_fkey",
               type: :uuid,
               prefix: "public",
               on_delete: :delete_all
             )
    end
  end

  def down do
    drop constraint(:place_users, "place_users_follower_id_fkey")

    alter table(:place_users) do
      modify :follower_id,
             references(:places,
               column: :id,
               name: "place_users_place_id_fkey",
               type: :uuid,
               prefix: "public",
               on_delete: :delete_all
             )
    end

    rename table(:place_users), :follower_id, to: :place_id
  end
end
