defmodule Foodmap.Repo.Migrations.Friends do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:friendships, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :status, :text, null: false, default: "pending"

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :user_id,
          references(:users,
            column: :id,
            name: "friendships_user_id_fkey",
            type: :uuid,
            prefix: "public"
          ), primary_key: true, null: false

      add :friend_id,
          references(:users,
            column: :id,
            name: "friendships_friend_id_fkey",
            type: :uuid,
            prefix: "public"
          ), primary_key: true, null: false
    end

    create unique_index(:friendships, [:user_id, :friend_id],
             name: "friendships_unique_friendship_index"
           )
  end

  def down do
    drop_if_exists unique_index(:friendships, [:user_id, :friend_id],
                     name: "friendships_unique_friendship_index"
                   )

    drop constraint(:friendships, "friendships_user_id_fkey")

    drop constraint(:friendships, "friendships_friend_id_fkey")

    drop table(:friendships)
  end
end
